In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
df = pd.read_csv("imdb_movies_dataset_project.csv")

In [22]:
df

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
0,Creed III,3/2/23,73,"Drama,¬†Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/22,78,"Science Fiction,¬†Adventure,¬†Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Salda√±a, Ney...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
2,The Super Mario Bros. Movie,4/5/23,76,"Animation,¬†Adventure,¬†Family,¬†Fantasy,¬†Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU
3,Mummies,1/5/23,70,"Animation,¬†Comedy,¬†Family,¬†Adventure,¬†Fantasy","Through a series of unfortunate events, three ...","√ìscar Barber√°n, Thut (voice), Ana Esther Alb...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU
4,Supercell,3/17/23,61,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",Supercell,Released,English,77000000.0,3.409420e+08,US
...,...,...,...,...,...,...,...,...,...,...,...,...
10173,20th Century Women,12/28/16,73,Drama,"In 1979 Santa Barbara, California, Dorothea Fi...","Annette Bening, Dorothea Fields, Lucas Jade Zu...",20th Century Women,Released,English,7000000.0,9.353729e+06,US
10174,Delta Force 2: The Colombian Connection,8/24/90,54,Action,When DEA agents are taken captive by a ruthles...,"Chuck Norris, Col. Scott McCoy, Billy Drago, R...",Delta Force 2: The Colombian Connection,Released,English,9145817.8,6.698361e+06,US
10175,The Russia House,12/21/90,61,"Drama,¬†Thriller,¬†Romance","Barley Scott Blair, a Lisbon-based editor of R...","Sean Connery, Bartholomew 'Barley' Scott Blair...",The Russia House,Released,English,21800000.0,2.299799e+07,US
10176,Darkman II: The Return of Durant,7/11/95,55,"Action,¬†Adventure,¬†Science Fiction,¬†Thrille...",Darkman and Durant return and they hate each o...,"Larry Drake, Robert G. Durant, Arnold Vosloo, ...",Darkman II: The Return of Durant,Released,English,116000000.0,4.756613e+08,US
10177,The Swan Princess: A Royal Wedding,7/20/20,70,"Animation,¬†Family,¬†Fantasy",Princess Odette and Prince Derek are going to ...,"Nina Herzog, Princess Odette (voice), Yuri Low...",The Swan Princess: A Royal Wedding,Released,English,92400000.0,5.394018e+08,GB

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10178 entries, 0 to 10177
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         10178 non-null  object
 1   release_date  10178 non-null  object
 2   score         10178 non-null  int64
 3   genre         10093 non-null  object
 4   overview      10178 non-null  object
 5   crew          10122 non-null  object
 6   orig_title    10178 non-null  object
 7   status        10178 non-null  object
 8   orig_lang     10178 non-null  object
 9   budget        10178 non-null  float64
 10  revenue       10178 non-null  float64
 11  country       10178 non-null  object
dtypes: float64(2), int64(1), object(9)
memory usage: 954.3+ KB

# FIRST PART: DATA CLEANING

#### dropping all duplicates

In [23]:
df.drop_duplicates()

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
0,Creed III,3/2/23,73,"Drama,¬†Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/22,78,"Science Fiction,¬†Adventure,¬†Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Salda√±a, Ney...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
2,The Super Mario Bros. Movie,4/5/23,76,"Animation,¬†Adventure,¬†Family,¬†Fantasy,¬†Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU
3,Mummies,1/5/23,70,"Animation,¬†Comedy,¬†Family,¬†Adventure,¬†Fantasy","Through a series of unfortunate events, three ...","√ìscar Barber√°n, Thut (voice), Ana Esther Alb...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU
4,Supercell,3/17/23,61,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",Supercell,Released,English,77000000.0,3.409420e+08,US
...,...,...,...,...,...,...,...,...,...,...,...,...
10173,20th Century Women,12/28/16,73,Drama,"In 1979 Santa Barbara, California, Dorothea Fi...","Annette Bening, Dorothea Fields, Lucas Jade Zu...",20th Century Women,Released,English,7000000.0,9.353729e+06,US
10174,Delta Force 2: The Colombian Connection,8/24/90,54,Action,When DEA agents are taken captive by a ruthles...,"Chuck Norris, Col. Scott McCoy, Billy Drago, R...",Delta Force 2: The Colombian Connection,Released,English,9145817.8,6.698361e+06,US
10175,The Russia House,12/21/90,61,"Drama,¬†Thriller,¬†Romance","Barley Scott Blair, a Lisbon-based editor of R...","Sean Connery, Bartholomew 'Barley' Scott Blair...",The Russia House,Released,English,21800000.0,2.299799e+07,US
10176,Darkman II: The Return of Durant,7/11/95,55,"Action,¬†Adventure,¬†Science Fiction,¬†Thrille...",Darkman and Durant return and they hate each o...,"Larry Drake, Robert G. Durant, Arnold Vosloo, ...",Darkman II: The Return of Durant,Released,English,116000000.0,4.756613e+08,US
10177,The Swan Princess: A Royal Wedding,7/20/20,70,"Animation,¬†Family,¬†Fantasy",Princess Odette and Prince Derek are going to ...,"Nina Herzog, Princess Odette (voice), Yuri Low...",The Swan Princess: A Royal Wedding,Released,English,92400000.0,5.394018e+08,GB

#### We have no duplicates

In [35]:
renaming_columns = {'names': 'title', 'date_x': 'release_date', 'overview': 'description', 'budget_x': 'budget'}
df.rename(columns = renaming_columns, inplace = True)

In [36]:
df["genre"] = df["genre"].str.replace("¬†", " ")
print(df["genre"])
df

0                                            Drama, Action
1                       Science Fiction, Adventure, Action
2            Animation, Adventure, Family, Fantasy, Comedy
3            Animation, Comedy, Family, Adventure, Fantasy
4                                                   Action
                               ...
10173                                                Drama
10174                                               Action
10175                             Drama, Thriller, Romance
10176    Action, Adventure, Science Fiction, Thriller, ...
10177                           Animation, Family, Fantasy
Name: genre, Length: 10178, dtype: object

,title,release_date,score,genre,description,crew,orig_title,status,orig_lang,budget,revenue,country
0,Creed III,3/2/23,73,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/22,78,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Salda√±a, Ney...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
2,The Super Mario Bros. Movie,4/5/23,76,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU
3,Mummies,1/5/23,70,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...","√ìscar Barber√°n, Thut (voice), Ana Esther Alb...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU
4,Supercell,3/17/23,61,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",Supercell,Released,English,77000000.0,3.409420e+08,US
...,...,...,...,...,...,...,...,...,...,...,...,...
10173,20th Century Women,12/28/16,73,Drama,"In 1979 Santa Barbara, California, Dorothea Fi...","Annette Bening, Dorothea Fields, Lucas Jade Zu...",20th Century Women,Released,English,7000000.0,9.353729e+06,US
10174,Delta Force 2: The Colombian Connection,8/24/90,54,Action,When DEA agents are taken captive by a ruthles...,"Chuck Norris, Col. Scott McCoy, Billy Drago, R...",Delta Force 2: The Colombian Connection,Released,English,9145817.8,6.698361e+06,US
10175,The Russia House,12/21/90,61,"Drama, Thriller, Romance","Barley Scott Blair, a Lisbon-based editor of R...","Sean Connery, Bartholomew 'Barley' Scott Blair...",The Russia House,Released,English,21800000.0,2.299799e+07,US
10176,Darkman II: The Return of Durant,7/11/95,55,"Action, Adventure, Science Fiction, Thriller, ...",Darkman and Durant return and they hate each o...,"Larry Drake, Robert G. Durant, Arnold Vosloo, ...",Darkman II: The Return of Durant,Released,English,116000000.0,4.756613e+08,US
10177,The Swan Princess: A Royal Wedding,7/20/20,70,"Animation, Family, Fantasy",Princess Odette and Prince Derek are going to ...,"Nina Herzog, Princess Odette (voice), Yuri Low...",The Swan Princess: A Royal Wedding,Released,English,92400000.0,5.394018e+08,GB

In [38]:
df["crew"][0]

"Michael B. Jordan, Adonis Creed, Tessa Thompson, Bianca Taylor, Jonathan Majors, Damien Anderson, Wood Harris, Tony 'Little Duke' Evers, Phylicia RashƒÅd, Mary Anne Creed, Mila Davis-Kent, Amara Creed, Florian Munteanu, Viktor Drago, Jos√© Benavidez Jr., Felix Chavez, Selenis Leyva, Laura Chavez"

In [24]:
#data.shape

In [23]:
#data.index

In [22]:
#data.columns

In [21]:
#data.dtypes

In [20]:
#data["status"].unique()

In [19]:
#data["status"].nunique()

In [18]:
#data.count()

In [17]:
#data["status"].value_counts()

In [16]:
#data.info()

In [15]:
#data[data['status'] == ' In Production']

In [5]:
#data[data["status"] == " Released"]

In [6]:
#data.isnull().sum()

In [7]:
#data.notnull().sum()

In [8]:
#data.rename(columns = {'status' : 'Status'})

In [11]:
#print(data["budget_x"].mean())
#print(data["budget_x"].std())
#print(data["revenue"].std())'''

In [12]:
#data.groupby("revenue")["budget_x"].mean()

In [175]:
#data["Status"] = data["Status"].str.lstrip()
#data["genre"] = data["genre"].str.replace('¬†', ' ')

In [14]:
#data.drop_duplicates()